AMS/Models/Assign/AssignBL.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Data;
using System.Data.SqlClient;
using System.Configuration;

namespace AMS.Models
{
    public class AssignBL
    {
        public string message;
        string constr = ConfigurationManager.ConnectionStrings["AMS"].ConnectionString;

        #region Assign Hardware
        public void AssignHw(AstAsgMultiview asgmulti)
        {
            using (SqlConnection con = new SqlConnection(constr))
            {
                SqlCommand cmdins = new SqlCommand("SP_ASTASGH", con);
                cmdins.CommandType = CommandType.StoredProcedure;
                cmdins.Parameters.AddWithValue("@ACTION", 1);
                cmdins.Parameters.AddWithValue("@MASSETTAG", asgmulti.HwAssetDet.ASSETTAG);
                cmdins.Parameters.AddWithValue("@CATGNAME", asgmulti.HwAssetDet.CATGNAME);
                cmdins.Parameters.AddWithValue("@BRAND", asgmulti.HwAssetDet.BRAND);
                cmdins.Parameters.AddWithValue("@MDLNAME", asgmulti.HwAssetDet.MDLNAME);
                cmdins.Parameters.AddWithValue("@SLNO", asgmulti.HwAssetDet.SLNO);
                cmdins.Parameters.AddWithValue("@CASSETTAG", asgmulti.AssetDet1.ASSETTAG);
                cmdins.Parameters.AddWithValue("@CCATGNAME", asgmulti.AssetDet1.CATGNAME);
                cmdins.Parameters.AddWithValue("@CBRAND", asgmulti.AssetDet1.BRAND);
                cmdins.Parameters.AddWithValue("@CMDLNAME", asgmulti.AssetDet1.MDLNAME);
                cmdins.Parameters.AddWithValue("@CSLNO", asgmulti.AssetDet1.SLNO);
                cmdins.Parameters.AddWithValue("@SERIALIZED", asgmulti.AssetDet1.SERIALIZED);
                cmdins.Parameters.AddWithValue("@QTY", asgmulti.AssetDet1.QTY);
                cmdins.Parameters.AddWithValue("@ASGDATE", asgmulti.AssetDet1.ASGDATE);
                cmdins.Parameters.AddWithValue("@RETDATE", "");
                cmdins.Parameters.AddWithValue("@RECDATE", asgmulti.AssetDet1.RECDATE);
                cmdins.Parameters.AddWithValue("@AUDTUSER", "ADMIN");
                cmdins.Parameters.Add("@MESSAGE", SqlDbType.VarChar, 500);
                cmdins.Parameters["@MESSAGE"].Direction = ParameterDirection.Output;
                con.Open();
                cmdins.ExecuteNonQuery();
                message = cmdins.Parameters["@MESSAGE"].Value.ToString();
            }
        }
        #endregion

        #region Assign Software
        public void AssignSw(AstAsgMultiview asgmulti)
        {
            using (SqlConnection con = new SqlConnection(constr))
            {
                SqlCommand cmdins = new SqlCommand("SP_ASTASGH", con);
                cmdins.CommandType = CommandType.StoredProcedure;
                cmdins.Parameters.AddWithValue("@ACTION", 2);
                cmdins.Parameters.AddWithValue("@MASSETTAG", asgmulti.HwAssetDet.ASSETTAG);
                cmdins.Parameters.AddWithValue("@CATGNAME", asgmulti.HwAssetDet.CATGNAME);
                cmdins.Parameters.AddWithValue("@BRAND", asgmulti.HwAssetDet.BRAND);
                cmdins.Parameters.AddWithValue("@MDLNAME", asgmulti.HwAssetDet.MDLNAME);
                cmdins.Parameters.AddWithValue("@SLNO", asgmulti.HwAssetDet.SLNO);
                cmdins.Parameters.AddWithValue("@CASSETTAG", asgmulti.AssetDet2.ASSETTAG);
                cmdins.Parameters.AddWithValue("@CCATGNAME", asgmulti.AssetDet2.CATGNAME);
                cmdins.Parameters.AddWithValue("@CBRAND", asgmulti.AssetDet2.BRAND);
                cmdins.Parameters.AddWithValue("@CMDLNAME", asgmulti.AssetDet2.MDLNAME);
                cmdins.Parameters.AddWithValue("@CSLNO", asgmulti.AssetDet2.SLNO);
                cmdins.Parameters.AddWithValue("@SERIALIZED", asgmulti.AssetDet2.SERIALIZED);
                cmdins.Parameters.AddWithValue("@QTY", asgmulti.AssetDet2.QTY);
                cmdins.Parameters.AddWithValue("@ASGDATE", asgmulti.AssetDet2.ASGDATE);
                cmdins.Parameters.AddWithValue("@RETDATE", "");
                cmdins.Parameters.AddWithValue("@RECDATE", asgmulti.AssetDet2.RECDATE);
                cmdins.Parameters.AddWithValue("@AUDTUSER", "ADMIN");
                cmdins.Parameters.AddWithValue("@LICTYPE", asgmulti.AssetDet2.LICTYPE);
                cmdins.Parameters.AddWithValue("@LICENSE", asgmulti.AssetDet2.LICENSE);
                cmdins.Parameters.Add("@MESSAGE", SqlDbType.VarChar, 500);
                cmdins.Parameters["@MESSAGE"].Direction = ParameterDirection.Output;
                con.Open();
                cmdins.ExecuteNonQuery();
                message = cmdins.Parameters["@MESSAGE"].Value.ToString();
            }
        }
        #endregion

        #region Assign Employee
        public void AssignEmp(AstAsgMultiview asgmulti)
        {
            using (SqlConnection con = new SqlConnection(constr))
            {
                SqlCommand cmdins = new SqlCommand("SP_ASTASGH", con);
                cmdins.CommandType = CommandType.StoredProcedure;
                cmdins.Parameters.AddWithValue("@ACTION", '3');
                cmdins.Parameters.AddWithValue("@MASSETTAG", asgmulti.HwAssetDet.ASSETTAG);
                cmdins.Parameters.AddWithValue("@CATGNAME", asgmulti.HwAssetDet.CATGNAME);
                cmdins.Parameters.AddWithValue("@BRAND", asgmulti.HwAssetDet.BRAND);
                cmdins.Parameters.AddWithValue("@MDLNAME", asgmulti.HwAssetDet.MDLNAME);
                cmdins.Parameters.AddWithValue("@SLNO", asgmulti.HwAssetDet.SLNO);
                cmdins.Parameters.AddWithValue("@EMPCODE", asgmulti.AssetDet3.EMPCODE);
                cmdins.Parameters.AddWithValue("@EMPNAME", asgmulti.AssetDet3.EMPNAME);
                cmdins.Parameters.AddWithValue("@DESG", asgmulti.AssetDet3.DESG);
                cmdins.Parameters.AddWithValue("@DEPT", asgmulti.AssetDet3.DEPT);
                cmdins.Parameters.AddWithValue("@DOJ", asgmulti.AssetDet3.DOJ);
                cmdins.Parameters.AddWithValue("@RPTMANAGER", asgmulti.AssetDet3.RPTMANAGER);
                cmdins.Parameters.AddWithValue("@EMPLOC", asgmulti.AssetDet3.EMPLOC);
                cmdins.Parameters.AddWithValue("@EMPCONT1", asgmulti.AssetDet3.EMPCONT1);
                cmdins.Parameters.AddWithValue("@EMPCONT2", asgmulti.AssetDet3.EMPCONT2);
                cmdins.Parameters.AddWithValue("@EMPEMAIL", asgmulti.AssetDet3.EMPEMAIL);
                cmdins.Parameters.AddWithValue("@GEOLOC", asgmulti.AssetDet3.GEOLOC);
                cmdins.Parameters.AddWithValue("@PHLOC", asgmulti.AssetDet3.PHLOC);
                cmdins.Parameters.AddWithValue("@ASGDATE", asgmulti.AssetDet3.ASGDATE);
                cmdins.Parameters.AddWithValue("@RETDATE", "");
                cmdins.Parameters.AddWithValue("@RECDATE", asgmulti.AssetDet3.RECDATE);
                cmdins.Parameters.AddWithValue("@AUDTUSER", "ADMIN");
                cmdins.Parameters.Add("@MESSAGE", SqlDbType.VarChar, 500);
                cmdins.Parameters["@MESSAGE"].Direction = ParameterDirection.Output;
                con.Open();
                cmdins.ExecuteNonQuery();
                message = cmdins.Parameters["@MESSAGE"].Value.ToString();
            }
        }
        #endregion

    }
}

AMS/Models/Assign/AssignContext.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Data.Entity;
namespace AMS.Models
{
    public class AssignContext : DbContext
    {
        public DbSet<AstHeader> asthdr { get; set; }
        public DbSet<AstAsgDet1> astdet1 { get; set; }
        public DbSet<AstAsgDet2> astdet2 { get; set; }
        public DbSet<AstAsgDet3> astdet3 { get; set; }
        public DbSet<HwAsset> hwdet { get; set; }
        public DbSet<SwAsset> swdet { get; set; }
        public DbSet<MsCategory> MsCategories { get; set; }
        public DbSet<MsVendor> MsVendors { get; set; }
    }
}

AMS/Models/Assign/AstAsgDet1.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;

namespace AMS.Models
{
    [Table("ASTASGD1")]
    
    public class AstAsgDet1
    {
        [Key]
        public int ID { get; set; }
        public string MASSETTAG { get; set; }
        public int LINENO { get; set; }
        public string ASSETTAG { get; set; }
        public string CATGNAME { get; set; }
        public string BRAND { get; set; }
        public string MDLNAME { get; set; }
        public string SLNO { get; set; }
        public int SERIALIZED { get; set; }
        public int QTY { get; set; }
        public int ASTSTS { get; set; }
        public string ASGDATE { get; set; }
        public string RETDATE { get; set; }
        public string RECDATE { get; set; }
        public string AUDTUSER { get; set; }
    }
}

AMS/Controllers/AssignController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;
using AMS.Models;
namespace AMS.Controllers
{
    public class AssignController : Controller
    {
        // GET: Assign
        public ActionResult Index()
        {
            return View();
        }
        public ActionResult AssignAsset()
        {
            initload();
            return View();
        }
        #region Intial Load
        public void initload()
        {

            AssignContext asg = new AssignContext();
            ViewBag.AssignDet1 = asg.astdet1.Where(x => x.MASSETTAG == "").ToList();
            ViewBag.AssignDet2 = asg.astdet2.Where(x => x.MASSETTAG == "").ToList();
            ViewBag.AssignDet3 = asg.astdet3.Where(x => x.MASSETTAG == "").ToList();

        }
        #endregion

        #region AssginRecord
        public void AssignDetRec(string asttag, AstAsgMultiview asgval)
        {
            HardwareContext hw = new HardwareContext();
            asgval.HwAssetDet = hw.hwdet.Where(x => x.SERIALIZED == 1 && x.HWSTS != 4).FirstOrDefault(x => x.ASSETTAG == asttag);
            AssignContext asgg = new AssignContext();
            ViewBag.AssignDet1 = asgg.astdet1.Where(x => x.MASSETTAG == asttag).ToList();
            ViewBag.AssignDet2 = asgg.astdet2.Where(x => x.MASSETTAG == asttag).ToList();
            ViewBag.AssignDet3 = asgg.astdet3.Where(x => x.MASSETTAG == asttag).ToList();
        }

        #endregion

        #region Asset Get
        public ActionResult AsgGet(string asttag, AstAsgMultiview asgval)
        {
            AssignDetRec(asttag, asgval);
            return View("AssignAsset", asgval);
        }
        #endregion

        #region Asset Get Det 1
        public ActionResult AsgGetD1(string asttag)
        {
            HardwareContext hwc = new HardwareContext();
            if (asttag != "")
            {

                HwAsset hwastdet = hwc.hwdet.FirstOrDefault(x => x.ASSETTAG == asttag);
                if (hwastdet != null)
                {
                    var divhwasg = new { hwcatgname = hwastdet.CATGNAME, hwbrand = hwastdet.BRAND, hwmdlname = hwastdet.MDLNAME, hwslno = hwastdet.SLNO, hwserialized = hwastdet.SERIALIZED , hwqty=hwastdet.QTY };
                    return Json(divhwasg, JsonRequestBehavior.AllowGet);
                }
                else
                {
                    return Json("", JsonRequestBehavior.AllowGet);
                }

            }
            else
            {
                return Json("", JsonRequestBehavior.AllowGet);
            }
        }
        #endregion

        #region Asset Get Det 2
        public ActionResult AsgGetD2(string asttag)
        {
            SoftwareContext swc = new SoftwareContext();
            if (asttag != "")
            {
                SwAsset swastdet = swc.swdet.FirstOrDefault(x => x.ASSETTAG == asttag);
                if (swastdet != null)
                {
                    var divswasg = new { swcatgname = swastdet.CATGNAME, swbrand = swastdet.BRAND, swmdlname = swastdet.MDLNAME, swslno = swastdet.SLNO, swqty = swastdet.USRLIC + swastdet.MACLIC };
                    return Json(divswasg, JsonRequestBehavior.AllowGet);
                }
                else
                {
                    return Json("", JsonRequestBehavior.AllowGet);
                }

            }
            else
            {
                return Json("", JsonRequestBehavior.AllowGet);
            }
        }
        #endregion

        #region Asset Get Det 3
        public ActionResult AsgGetD3(string empcode)
        {
            AssignContext asg = new AssignContext();
            if (empcode != "")
            {
                AstAsgDet3 asgdet3= asg.astdet3.FirstOrDefault(x => x.EMPCODE == empcode);
                if (asgdet3 != null)
                {
                    var divempasg = new { empasgcode = asgdet3.EMPCODE, empasgasset=asgdet3.MASSETTAG };
                    return Json(divempasg, JsonRequestBehavior.AllowGet);
                }
                else
                {
                    return Json("", JsonRequestBehavior.AllowGet);
                }

            }
            else
            {
                return Json("", JsonRequestBehavior.AllowGet);
            }
        }
        #endregion

        #region Assign Detail 1

        public ActionResult AsgHwIns(AstAsgMultiview asghwins)
        {
            string message = "";
            try
            {
                if (ModelState.IsValid)
                {
                    AssignBL ashwbl = new AssignBL();
                    UpdateModel<AstAsgMultiview>(asghwins);
                    ashwbl.AssignHw(asghwins);
                    message = ashwbl.message;
                }
            }
            catch (Exception ex)
            {
                message = ex.ToString();
                Response.Write(message);
            }
            ModelState.Clear();

            List<AstAsgMultiview> lstAsgMulView = new List<AstAsgMultiview>();
            AssignDetRec(asghwins.HwAssetDet.ASSETTAG, asghwins);
            lstAsgMulView.Add(asghwins);
            return View("_AssignHwDet", lstAsgMulView);
        }
        #endregion

        #region Assign Detail2
        public ActionResult AsgSwIns(AstAsgMultiview asgswins)
        {
            string message = "";
            try
            {
                if (ModelState.IsValid)
                {
                    AssignBL asswbl = new AssignBL();
                    UpdateModel<AstAsgMultiview>(asgswins);
                    asswbl.AssignSw(asgswins);
                    message = asswbl.message;
                }
            }
            catch (Exception ex)
            {
                message = ex.ToString();
                Response.Write(message);
            }
            ModelState.Clear();

            List<AstAsgMultiview> lstAsgMulViewsw = new List<AstAsgMultiview>();
            AssignDetRec(asgswins.HwAssetDet.ASSETTAG, asgswins);
            lstAsgMulViewsw.Add(asgswins);
            return View("_AssignSwDet", lstAsgMulViewsw);
        }
        #endregion

        #region Assign Detail3
        public ActionResult AsgEmpIns(AstAsgMultiview asgempins)
        {
            string message = "";
            try
            {
                if (ModelState.IsValid)
                {
                    AssignBL asbl = new AssignBL();
                    UpdateModel<AstAsgMultiview>(asgempins);
                    asbl.AssignEmp(asgempins);
                    message = asbl.message;
                }
            }
            catch (Exception ex)
            {
                message = ex.ToString();
                Response.Write(message);
            }
            ModelState.Clear();

            List<AstAsgMultiview> lstAsgMulView = new List<AstAsgMultiview>();
            AssignDetRec(asgempins.HwAssetDet.ASSETTAG, asgempins);
            lstAsgMulView.Add(asgempins);
            return View("_AssignEmpDet", lstAsgMulView);
        }
        #endregion

        #region Auto Fill Master Get
        public JsonResult GetMasteDet(string invvalue)
        {
            HardwareContext hw = new HardwareContext();
            var hardware = hw.hwdet.Where(a => a.SERIALIZED == 1 && a.HWSTS != 4);
            var invnumber = (from inv in hardware where inv.ASSETTAG.Contains(invvalue) || inv.CATGNAME.Contains(invvalue) || inv.SLNO.Contains(invvalue) select new { inv.ASSETTAG, inv.CATGNAME, inv.SLNO });
            return Json(invnumber, JsonRequestBehavior.AllowGet);
        }
        #endregion

        #region Auto Fill Asset Get 1
        public JsonResult GetAssetDet1(string inhwval)
        {
            HardwareContext hw = new HardwareContext();
            var hardet = hw.hwdet.Where(a => a.HWSTS == 1);
            var invhwnumber= (from inv in hardet where inv.ASSETTAG.Contains(inhwval) || inv.CATGNAME.Contains(inhwval) || inv.SLNO.Contains(inhwval) select new { inv.ASSETTAG, inv.CATGNAME, inv.SLNO });
            return Json(invhwnumber, JsonRequestBehavior.AllowGet);
        }
        #endregion

        #region Auto Fill Asset Get 2
        public JsonResult GetAssetDet2(string inswval)
        {
            SoftwareContext sw = new SoftwareContext();
            var softdet = sw.swdet.Where(a => a.SWSTS == 1);
            var invswnumber = (from inv in softdet where inv.ASSETTAG.Contains(inswval) || inv.CATGNAME.Contains(inswval) || inv.SLNO.Contains(inswval) select new { inv.ASSETTAG, inv.CATGNAME, inv.SLNO });
            return Json(invswnumber, JsonRequestBehavior.AllowGet);
        }
        #endregion
    }
}

AMS/Views/Assign/AssignAsset.cshtml
@model AMS.Models.AstAsgMultiview

@{
    ViewBag.Title = "Assign Assets";
    Layout = "~/Views/Shared/_LayoutAdmin.cshtml";
}
@*<link rel="stylesheet" href="//code.jquery.com/ui/1.12.1/themes/base/jquery-ui.css">
<script type="text/javascript" src="http://ajax.googleapis.com/ajax/libs/jquery/1.8.3/jquery.min.js"></script>
<script src="~/Scripts/jquery.validate.js"></script>
<script src="~/Scripts/jquery-1.8.0.min.js"></script>
<script src="~/Scripts/jquery.validate.min.js"></script>
<script src="~/Scripts/jquery.validate.unobtrusive.min.js"></script>
<script type="text/javascript" src="~/Js/Validation.js"></script>
<script src="https://code.jquery.com/jquery-1.12.4.js"></script>
<script src="https://code.jquery.com/ui/1.12.1/jquery-ui.js"></script>*@


<div class="w3-container">
    <header class="w3-container w3-card-4 w3-theme w3-teal">
        <h3>Assign Asset</h3>
    </header>
    @using (Html.BeginForm("AssignAsset", "Assign", FormMethod.Post, new { @class = "w3-container", @id = "assetform", enctype = "multipart/form-data" }))
    {
        <div class="w3-container">@Html.Partial("_AssignHeader")</div>
        <div class="w3-container">@Html.Partial("_AssignHw")</div>
        <div class="w3-container">@Html.Partial("_AssignSw")</div>
        <div class="w3-container">@Html.Partial("_AssignEmp")</div>
    }
</div>
<script>
    $(document).ready(function () {
        initdatepicker();
    });
    function initdatepicker() {
        $(".datepicker").datepicker({
            dateFormat: 'dd-mm-yy',
            changeMonth: true,
            changeYear: true
        });
    }
</script>

AMS/Views/Assign/_AssignEmpDet.cshtml
@model IList<AMS.Models.AstAsgMultiview>
<div class="w3-responsive">
    <table class="w3-table-all" border="1">
        <thead>
            <tr class="w3-teal">
                <th>View</th>
                <th>Employee Code</th>
                <th>Name</th>
                <th>Designation</th>
                <th>Department</th>
                <th>Location</th>
            </tr>
        </thead>
        <tbody>
            @foreach (var item in ViewBag.AssignDet3)
            {
                <tr>
                    <td>
                        @Html.ActionLink("View", "View", new { catcode = item.ID })
                    </td>
                    <td>
                        @item.EMPCODE
                    </td>
                    <td>
                        @item.EMPNAME
                    </td>
                    <td>
                        @item.DESG
                    </td>
                    <td>
                        @item.DEPT
                    </td>
                    <td>
                        @item.EMPLOC
                    </td>
                </tr>
            }
        </tbody>
    </table>
</div>

AMS/Views/Assign/_AssignHeader.cshtml
@model AMS.Models.AstAsgMultiview



<div class="w3-row-padding">
    <div class="w3-col l4">
        <p>
            <label class="w3-text-teal">Asset Tag</label>
        </p>
        <p>
            @Html.TextBoxFor(m => m.HwAssetDet.ASSETTAG, new { @id = "ASSETTAG", @style = "width:200px;text-transform:uppercase;border:0px 0px 1px 0px;" })
            &nbsp;&nbsp;
            <a onclick="NewClick();"><img src="~/Images/new.png" width="20" height="20" /></a>
        </p>
        <p>
            <label class="w3-text-teal">Category Type</label>
            @*@Html.DropDownListFor(m => m.CATGNAME, new SelectList(ViewBag.hwcatg, "CATGNAME", "CATGDESC"), "--- Select ---", new { @class = "w3-input", @id = "CATGNAME" })*@
            @Html.TextBoxFor(m => m.HwAssetDet.CATGNAME, new { @class = "w3-input", @id = "CATGNAME", @style = "background-color:#e6e6e6;", @readonly = "true" })
        </p>
    </div>
    <div class="w3-col l4">
        <p>
            <label class="w3-text-teal">Brand</label>
            @Html.TextBoxFor(m => m.HwAssetDet.BRAND, new { @class = "w3-input", @id = "BRAND", @style = "background-color:#e6e6e6;", @readonly = "true" })
        </p>
        <p>
            <label class="w3-text-teal">Model Name</label>
            @Html.TextBoxFor(m => m.HwAssetDet.MDLNAME, new { @class = "w3-input", @id = "MDLNAME", @style = "background-color:#e6e6e6;", @readonly = "true" })
        </p>
    </div>
    <div class="w3-col l4">
        <p>
            <label class="w3-text-teal">Serial Number</label>
            @Html.TextBoxFor(m => m.HwAssetDet.SLNO, new { @class = "w3-input", @id = "SLNO", @style = "background-color:#e6e6e6;", @readonly = "true" })
        </p>
        <p>
            <label class="w3-text-teal">Last Maintained At</label>
            @Html.TextBoxFor(m => m.HwAssetDet.DATELASTMN, new { @class = "w3-input", @id = "DATELASTMN", @style = "background-color:#e6e6e6;", @readonly = "true" })
        </p>
    </div>
</div>
<script>
    $(document).ready(function () {
        $("#ASSETTAG").autocomplete({
            source: function (request, response) {
                $.ajax({
                    url: "/Assign/GetMasteDet",
                    type: "POST",
                    dataType: "json",
                    data: { invvalue: request.term },
                    success: function (data) {
                        response($.map(data, function (item) {
                            return { label: item.ASSETTAG + ' ' + item.CATGNAME + ' ' + item.SLNO, value: item.ASSETTAG };
                        }))

                    }
                })
            },
            messages: {
                noResults: "",
                results: function (count) {
                    return count + (count > 1 ? ' results' : ' result ') + ' found';
                }
            }
        });
    });
    var SelectAssetKey;
    $("#ASSETTAG").change(function () {
        SelectAssetKey = $("#ASSETTAG").val().trim();
        if (SelectAssetKey === "") {

        }
        else {
            getAssetTable();
           
        }
    });
    function getAssetTable() {

        $.ajax({
            url: "/Assign/AsgGet",
            type: 'Get',
            data: { asttag: SelectAssetKey },
            success: function (data) {
                $("#overright").empty().append(data);
                if ($("#ASSETTAG").val().trim() != " ") {

                    $("#ASGHWBTN").show();
                    $("#ASGSWBTN").show();
                    $("#ASGEMPBTN").show();
                }
                else {
                    $("#ASGHWBTN").hide();
                    $("#ASGSWBTN").hide();
                    $("#ASGEMPBTN").hide();
                }
            },
            error: function () {
                alert("something seems wrong");
            }
        });
    }
    function NewClick() {
        SelectAssetKey = "";
        getAssetTable();
    }
    
</script>

AMS/Views/Assign/_AssignHwDet.cshtml
@model IList<AMS.Models.AstAsgMultiview>
<div class="w3-responsive">
    <table class="w3-table-all" border="1">
        <thead>
            <tr class="w3-teal">
                <th>View</th>
                <th>Asset Tag</th>
                <th>Category</th>
                <th>Brand</th>
                <th>Model</th>
                <th>Serial No</th>
                <th>Quantity</th>
            </tr>
        </thead>
        <tbody>
            @foreach (var item in ViewBag.AssignDet1)
            {
                <tr>
                    <td>
                        @Html.ActionLink("View", "View", new { catcode = item.ID })
                    </td>
                    <td>
                        @item.ASSETTAG
                    </td>
                    <td>
                        @item.CATGNAME
                    </td>
                    <td>
                        @item.BRAND
                    </td>
                    <td>
                        @item.MDLNAME
                    </td>
                    <td>
                        @item.SLNO
                    </td>
                    <td>
                        @item.QTY
                    </td>
                </tr>
            }
        </tbody>
    </table>
</div>

AMS/Views/Assign/_AssignSwDet.cshtml
@model IList<AMS.Models.AstAsgMultiview>
<div class="w3-responsive">
    <table class="w3-table-all" border="1">
        <thead>
            <tr class="w3-teal">
                <th>View</th>
                <th>Asset Tag</th>
                <th>Category</th>
                <th>Brand</th>
                <th>Model</th>
                <th>Serial No</th>
                <th>Quantity</th>
            </tr>
        </thead>
        <tbody>
            @foreach (var item in ViewBag.AssignDet2)
            {
                <tr>
                    <td>
                        @Html.ActionLink("View", "View", new { catcode = item.ID })
                    </td>
                    <td>
                        @item.ASSETTAG
                    </td>
                    <td>
                        @item.CATGNAME
                    </td>
                    <td>
                        @item.BRAND
                    </td>
                    <td>
                        @item.MDLNAME
                    </td>
                    <td>
                        @item.SLNO
                    </td>
                    <td>
                        @item.QTY
                    </td>
                </tr>
            }
        </tbody>
    </table>
</div>